const products=[
{name:'iPhone 16',meta:'A18 · 6.1-inch display',img:'assets/iphone16.png'},
{name:'iPhone 16 Plus',meta:'A18 · 6.7-inch display',img:'assets/iphone16plus.png'},
{name:'iPhone 17',meta:'A19 · 6.3-inch ProMotion',img:'assets/iphone17.png'},
{name:'iPhone 17 Pro',meta:'A19 Pro · Pro camera system',img:'assets/iphone17pro.png'},
{name:'iPhone 17 Pro Max',meta:'A19 Pro · 6.9-inch display',img:'assets/iphone17promax.png'}
];
const track=document.getElementById('track'),stage=document.getElementById('stage'),nameEl=document.getElementById('modelName'),metaEl=document.getElementById('modelMeta'),dotsEl=document.getElementById('dots');let active=2,dragX=0,startX=0,dragging=false,wheelLock=false;
products.forEach((p,i)=>{const c=document.createElement('article');c.className='card';c.innerHTML=`<div class="phone-wrap"><img src="${p.img}" alt="${p.name}"></div><div class="card-label">${p.name}</div>`;c.addEventListener('click',()=>{active=i;render()});track.appendChild(c);const d=document.createElement('span');d.className='dot';dotsEl.appendChild(d)});
const cards=[...document.querySelectorAll('.card')],dots=[...document.querySelectorAll('.dot')];
function render(){cards.forEach((c,i)=>{let diff=i-active;if(diff>2)diff-=products.length;if(diff<-2)diff+=products.length;const x=diff*98;const z=-Math.abs(diff)*88;const ry=diff*-23;const scale=diff===0?1:Math.max(.76,1-Math.abs(diff)*.12);c.style.transform=`translate3d(${x}px,0,${z}px) rotateY(${ry}deg) scale(${scale})`;c.style.opacity=Math.abs(diff)>2?0:1-Math.abs(diff)*.16;c.style.filter=diff===0?'saturate(1.05)':'saturate(.72) brightness(.78)';c.style.zIndex=10-Math.abs(diff);c.classList.toggle('active',diff===0)});dots.forEach((d,i)=>d.classList.toggle('active',i===active));nameEl.animate([{opacity:.2,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:420,easing:'ease-out'});nameEl.textContent=products[active].name;metaEl.textContent=products[active].meta}
function go(n){active=(active+n+products.length)%products.length;render()}
document.getElementById('next').onclick=()=>go(1);document.getElementById('prev').onclick=()=>go(-1);
stage.addEventListener('wheel',e=>{e.preventDefault();if(wheelLock)return;wheelLock=true;go((e.deltaY||e.deltaX)>0?1:-1);setTimeout(()=>wheelLock=false,560)},{passive:false});
stage.addEventListener('pointerdown',e=>{dragging=true;startX=e.clientX;stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!dragging)return;dragX=e.clientX-startX;track.style.transform=`translateX(${dragX*.18}px)`});stage.addEventListener('pointerup',e=>{dragging=false;track.style.transform='';if(Math.abs(dragX)>38)go(dragX<0?1:-1);dragX=0});window.addEventListener('keydown',e=>{if(e.key==='ArrowRight')go(1);if(e.key==='ArrowLeft')go(-1)});render();
// subtle Apple-like Three.js background
const canvas=document.getElementById('bg');const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,100);camera.position.z=7;const group=new THREE.Group();scene.add(group);const geo=new THREE.TorusKnotGeometry(1.65,.34,180,28);const mat=new THREE.MeshPhysicalMaterial({color:0x1d1d1f,metalness:.55,roughness:.18,transmission:.12,transparent:true,opacity:.55});const knot=new THREE.Mesh(geo,mat);group.add(knot);const light1=new THREE.PointLight(0x8ab4ff,12,20);light1.position.set(3,2,4);scene.add(light1);const light2=new THREE.PointLight(0xff8a55,9,18);light2.position.set(-4,-2,3);scene.add(light2);function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}resize();addEventListener('resize',resize);let t=0;function loop(){t+=.004;knot.rotation.x=t*.45;knot.rotation.y=t*.68;group.position.y=Math.sin(t*1.3)*.18;renderer.render(scene,camera);requestAnimationFrame(loop)}loop();
